//
//  AppointmentInteractor.swift
//  Enrich_SMA
//
//  Created by Harshal Patil on 22/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AppointmentBusinessLogic {
    func doGetAppointmentList(request: Appointment.GetAppointnents.Request, method: HTTPMethod)
}

protocol AppointmentDataStore {
    //var name: String { get set }
}

class AppointmentInteractor: AppointmentBusinessLogic, AppointmentDataStore {
    var presenter: AppointmentPresentationLogic?
    var worker: AppointmentWorker?
    //var name: String = ""

    // MARK: Do something

    func doGetAppointmentList(request: Appointment.GetAppointnents.Request, method: HTTPMethod) {
        worker = AppointmentWorker()
        worker?.presenter = self.presenter
        worker?.postRequestForAppointments(request: request, method: method)
    }
}
