//
//  PackageFilterInteractor.swift
//  Enrich_SMA
//
//  Created by Harshal on 27/01/22.
//  Copyright (c) 2022 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PackageFilterBusinessLogic
{
  func doSomething(request: PackageFilter.Something.Request)
}

protocol PackageFilterDataStore
{
  //var name: String { get set }
}

class PackageFilterInteractor: PackageFilterBusinessLogic, PackageFilterDataStore
{
  var presenter: PackageFilterPresentationLogic?
  var worker: PackageFilterWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: PackageFilter.Something.Request)
  {
    worker = PackageFilterWorker()
    worker?.doSomeWork()
    
    let response = PackageFilter.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
