//
//  FreeServicesInteractor.swift
//  Enrich_SMA
//
//  Created by Harshal on 21/01/22.
//  Copyright (c) 2022 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FreeServicesBusinessLogic
{
  func doSomething(request: FreeServices.Something.Request)
}

protocol FreeServicesDataStore
{
  //var name: String { get set }
}

class FreeServicesInteractor: FreeServicesBusinessLogic, FreeServicesDataStore
{
  var presenter: FreeServicesPresentationLogic?
  var worker: FreeServicesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: FreeServices.Something.Request)
  {
    worker = FreeServicesWorker()
    worker?.doSomeWork()
    
    let response = FreeServices.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
