//
//  ClientInformationPresenter.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 08/11/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClientInformationPresentationLogic
{
  func presentSomething(response: ClientInformation.Something.Response)
}

class ClientInformationPresenter: ClientInformationPresentationLogic
{
  weak var viewController: ClientInformationDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ClientInformation.Something.Response)
  {
    let viewModel = ClientInformation.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
