//
//  ClientInformationPresenter.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 08/11/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClientInformationPresentationLogic
{
    func presentGetAppointmentHistorySuccess<T: Decodable>(response: T)
    func presentGetMembershipDetailsSuccess<T: Decodable>(response: T)
    func presentGetClientPreferenceSuccess<T: Decodable>(response: T)
    func presentGetClientNotesSuccess<T: Decodable>(response: T)
    func presentError(responseError: String?)
}

class ClientInformationPresenter: ClientInformationPresentationLogic
{
    weak var viewController: ClientInformationDisplayLogic?
    
    // MARK: Do something
    
    func presentGetAppointmentHistorySuccess<T>(response: T) where T : Decodable {
        viewController?.displaySuccess(viewModel: response)
    }
    
    func presentGetMembershipDetailsSuccess<T>(response: T) where T : Decodable {
        viewController?.displaySuccess(viewModel: response)
    }
    
    func presentError(responseError: String?) {
        viewController?.displayError(errorMessage: responseError)
    }
    
    func presentGetClientPreferenceSuccess<T: Decodable>(response: T){
        viewController?.displaySuccess(viewModel: response)
    }
    
    func presentGetClientNotesSuccess<T: Decodable>(response: T){
        viewController?.displaySuccess(viewModel: response)
    }
}
