//
//  ClientInformationWorker.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 08/11/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ClientInformationWorker
{
    let networkLayer = NetworkLayerAlamofire() // Uncomment this in case do request using Alamofire for client request
    var presenter: ClientInformationPresentationLogic?
    
    func postRequestForAppointmentHistory(request:ClientInformation.GetAppointnentHistory.Request, method: HTTPMethod) {
        
        let errorHandler: (String) -> Void = { (error) in
            print(error)
            self.presenter?.presentError(responseError: error)
        }
        let successHandler: (ClientInformation.GetAppointnentHistory.Response) -> Void = { (response) in
            self.presenter?.presentGetAppointmentHistorySuccess(response: response)
        }
        
        self.networkLayer.post(urlString: ConstantAPINames.getAppointments.rawValue, body: request, headers: ["X-Request-From": "tma"], successHandler: successHandler, errorHandler: errorHandler, method: method)
    }
    
    func getRequestForMembershipDetails(accessToken:String, method: HTTPMethod,request: ClientInformation.MembershipDetails.Request) {
        
        let errorHandler: (String) -> Void = { (error) in
            print(error)
            self.presenter?.presentError(responseError: error)
        }
        
        let successHandler: (ClientInformation.MembershipDetails.Response) -> Void = { (response) in
            self.presenter?.presentGetMembershipDetailsSuccess(response: response)
        }
        
        let url = "\(ConstantAPINames.membershipDetails.rawValue)&customer_id=\(request.customer_id)"
                
        self.networkLayer.get(urlString: url, successHandler: successHandler, errorHandler: errorHandler)
    }
    
    func getRequestForClientPreference(accessToken:String, method: HTTPMethod,request: ClientInformation.Preferences.Request) {
        
        let errorHandler: (String) -> Void = { (error) in
            print(error)
            self.presenter?.presentError(responseError: error)
        }
        
        let successHandler: (ClientInformation.Preferences.Response) -> Void = { (response) in
            self.presenter?.presentGetClientPreferenceSuccess(response: response)
        }
        
        let url = "\(ConstantAPINames.clientPreferences.rawValue)&customer_id=\(request.customer_id)"
        
        self.networkLayer.get(urlString: url, successHandler: successHandler, errorHandler: errorHandler)
    }
    
    func getRequestForClientNotes(accessToken:String, method: HTTPMethod,request: ClientInformation.ClientNotes.Request) {
        
        let errorHandler: (String) -> Void = { (error) in
            print(error)
            self.presenter?.presentError(responseError: error)
        }
        
        let successHandler: (ClientInformation.ClientNotes.Response) -> Void = { (response) in
            self.presenter?.presentGetClientNotesSuccess(response: response)
        }
        
        let url = "\(ConstantAPINames.clientNotes.rawValue)&customer_id=\(request.customer_id)"
        
        self.networkLayer.get(urlString: url, successHandler: successHandler, errorHandler: errorHandler)
    }
    
}
