//
//  ClientInformationInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 08/11/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClientInformationBusinessLogic
{
  func doSomething(request: ClientInformation.Something.Request)
}

protocol ClientInformationDataStore
{
  //var name: String { get set }
}

class ClientInformationInteractor: ClientInformationBusinessLogic, ClientInformationDataStore
{
  var presenter: ClientInformationPresentationLogic?
  var worker: ClientInformationWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ClientInformation.Something.Request)
  {
    worker = ClientInformationWorker()
    worker?.doSomeWork()
    
    let response = ClientInformation.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
