//
//  RequestDetailsInteractor.swift
//  Enrich_SMA
//
//  Created by Harshal on 05/05/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RequestDetailsBusinessLogic {
  func doSomething(request: RequestDetails.Something.Request)
}

protocol RequestDetailsDataStore {
  //var name: String { get set }
}

class RequestDetailsInteractor: RequestDetailsBusinessLogic, RequestDetailsDataStore {
  var presenter: RequestDetailsPresentationLogic?
  var worker: RequestDetailsWorker?
  //var name: String = ""

  // MARK: Do something

  func doSomething(request: RequestDetails.Something.Request) {
    worker = RequestDetailsWorker()
    worker?.doSomeWork()

    let response = RequestDetails.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
