//
//  SalesPresenter.swift
//  Enrich_SMA
//
//  Created by Harshal on 21/01/22.
//  Copyright (c) 2022 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SalesPresentationLogic
{
  func presentSomething(response: Sales.Something.Response)
}

class SalesPresenter: SalesPresentationLogic
{
  weak var viewController: SalesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Sales.Something.Response)
  {
    let viewModel = Sales.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
