//
//  DashboardModels.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 15/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Dashboard {

  // MARK: Use cases
    enum GetDashboardData {

        struct Request: Codable {
            let is_custom: Bool
            let salon_id: String
        }

        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
            var count: Int?
        }
    }
}
