//
//  DashboardModels.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 15/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Dashboard {

    // MARK: Use cases
    enum GetDashboardData {

        struct Request: Codable {
            let is_custom: Bool
            let salon_id: String
        }

        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
            var data: Data?
        }

        struct Data: Codable {
            let daily_revenue_data: [revenueData]?
            let monthly_revenue_data: [revenueData]?
        }

        struct revenueData: Codable {
            let entity_id: String?
            let salon_id: String?
            let salon_name: String?
            let monthly_date: String?
            let membership_target: String?
            let membership_revenue: String?
            let membership_sold_percentage: Double?
            let service_target: String?
            let service_revenue: String?
            let service_revenue_percentage: Double?
            let products_target: String?
            let products_revenue: String?
            let products_revenue_percentage: Double?
            let sales_modified: String?
            let total_collection: String?
            let total_net_revenue: String?
            let total_gross_sales: String?
            let total_gross_revenue: String?
            let runrate_percentage: Double?
        }
    }
    enum GetForceUpadateInfo {

        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
            var data: Data?
        }

        struct Data: Codable {
            let force_update_info: ForceUpdateInfo?
        }

        struct ForceUpdateInfo: Codable {
            let tma_ios: Info?
            let sma_ios: Info?
        }

        struct Info: Codable {
            let latest_version: String?
            let force_update: Bool?
            let app_link: String?
        }
    }
}
