//
//  SOSAlertModels.swift
//  Enrich_SMA
//
//  Created by Harshal on 03/04/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SOSAlert
{
    // MARK: Use cases
    
    enum SendFeedback {
        
        struct Request: Codable {
            let employee_id: String
            let message: String
            let sent_by_id: String
            let is_custom: Int
            let acknowledgedNotificationId: String
        }
        
        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
            var count: Int?
        }
    }
}
