//
//  SOSAlertViewController.swift
//  Enrich_SMA
//
//  Created by Harshal on 03/04/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SOSAlertDisplayLogic: class {
    func displaySuccess<T: Decodable> (viewModel: T)
    func displayError(errorMessage: String?)
}

class SOSAlertVC: UIViewController, SOSAlertDisplayLogic {
    var interactor: SOSAlertBusinessLogic?

    @IBOutlet weak private var profilePicture: UIImageView!
    @IBOutlet weak private var lblUserName: UILabel!
    @IBOutlet weak private var lblLevel: UILabel!
    @IBOutlet weak private var btnMobileNo: UIButton!
    @IBOutlet weak private var lblAddress: UILabel!
    @IBOutlet weak private var txtfMessage: UITextField!
    @IBOutlet weak private var btnOk: UIButton!

    var viewDismissBlock: ((Bool) -> Void)?

    var alertData: Notifications.MyNotificationList.MyNotificationListItems?

    var profileData: MyProfile.GetUserProfile.UserData?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = SOSAlertInteractor()
        let presenter = SOSAlertPresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        getusershell()
        txtfMessage.delegate = self
        [txtfMessage].forEach({ $0.addTarget(self, action: #selector(editingChanged), for: .editingChanged) })
    }

    func configureUI() {
        if let alertData = alertData,
            let profileData = profileData {
            lblUserName.text = "\(profileData.firstname ?? "") \(profileData.lastname ?? "")"
            lblLevel.text = profileData.designation ?? ""
            btnMobileNo.setTitle(profileData.mobile_number, for: .normal)
            lblAddress.text = alertData.data ?? ""
        }
    }

    func getProfileData() {
        EZLoadingActivity.show("Loading...", disableUI: true)
        interactor?.doGetMyProfileData(employeeId: 34)
    }

    @IBAction func actionMobileNo(_ sender: UIButton) {
    }

    @IBAction func actionOK(_ sender: UIButton) {
        if btnOk.isEnabled {
            sendSOSFeedback()
        }
    }
}

// MARK: Call Webservice
extension SOSAlertVC {

    func sendSOSFeedback() {
        if let userData = UserDefaults.standard.value(MyProfile.GetUserProfile.UserData.self, forKey: UserDefauiltsKeys.k_Key_LoginUser) {
            EZLoadingActivity.show("Loading...", disableUI: true)
            let request = SOSAlert.SendFeedback.Request(employee_id: userData.employee_id ?? "", message: txtfMessage.text ?? "", sent_by_id: "", is_custom: 1, acknowledgedNotificationId: "")
            interactor?.doPostSendSOSFeedback(request: request, method: .post)
        }
    }

    func displaySuccess<T: Decodable>(viewModel: T) {
        EZLoadingActivity.hide()
        if let model = viewModel as? SOSAlert.SendFeedback.Response,
            model.status == true {
            viewDismissBlock?(true)
            self.dismiss(animated: true, completion: nil)
        }
        else if let model = viewModel as? MyProfile.GetUserProfile.Response {
            self.profileData = model.data
            configureUI()
        }
    }
    func displayError(errorMessage: String?) {
        EZLoadingActivity.hide()
        DispatchQueue.main.async { [unowned self] in
            self.showAlert(alertTitle: alertTitle, alertMessage: errorMessage ?? "")
        }
    }
}

extension SOSAlertVC: UITextFieldDelegate {

    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        textField.resignFirstResponder()
        return true
    }

    func textFieldShouldEndEditing(_ textField: UITextField) -> Bool {
        textField.resignFirstResponder()
        return true
    }
}

extension SOSAlertVC {
    @objc func editingChanged(_ textField: UITextField) {
        btnOk.isEnabled = false
        let message = (txtfMessage.text ?? "").trim()
        if !message.isEmpty {
            btnOk.isEnabled = true
        }
    }
}
