//
//  SOSAlertInteractor.swift
//  Enrich_SMA
//
//  Created by Harshal on 03/04/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SOSAlertBusinessLogic {
    func doPostSendSOSFeedback(request: SOSAlert.SendFeedback.Request, method: HTTPMethod)
}

protocol SOSAlertDataStore {
    //var name: String { get set }
}

class SOSAlertInteractor: SOSAlertBusinessLogic, SOSAlertDataStore {
    var presenter: SOSAlertPresentationLogic?
    var worker: SOSAlertWorker?
    //var name: String = ""

    // MARK: Do something

    func doPostSendSOSFeedback(request: SOSAlert.SendFeedback.Request, method: HTTPMethod) {
        worker = SOSAlertWorker()
        worker?.presenter = self.presenter
        worker?.postSendSOSFeedback(request: request, method: method)
    }
}
