//
//  ResourceUtilisationInteractor.swift
//  Enrich_SMA
//
//  Created by Harshal on 21/01/22.
//  Copyright (c) 2022 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ResourceUtilisationBusinessLogic
{
  func doSomething(request: ResourceUtilisation.Something.Request)
}

protocol ResourceUtilisationDataStore
{
  //var name: String { get set }
}

class ResourceUtilisationInteractor: ResourceUtilisationBusinessLogic, ResourceUtilisationDataStore
{
  var presenter: ResourceUtilisationPresentationLogic?
  var worker: ResourceUtilisationWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ResourceUtilisation.Something.Request)
  {
    worker = ResourceUtilisationWorker()
    worker?.doSomeWork()
    
    let response = ResourceUtilisation.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
