//
//  ListingInteractor.swift
//  Enrich_SMA
//
//  Created by Harshal on 14/07/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListingBusinessLogic {
    func doGetRosterData(request: MyProfile.GetRosterDetails.Request, method: HTTPMethod)
    func doGetServiceListData(employeeId: String?)
}

protocol ListingDataStore {
    //var name: String { get set }
}

class ListingInteractor: ListingBusinessLogic, ListingDataStore {
    var presenter: ListingPresentationLogic?
    var worker: ListingWorker?
    //var name: String = ""

    // MARK: Do something

    func doGetRosterData(request: MyProfile.GetRosterDetails.Request, method: HTTPMethod) {
        worker = ListingWorker()
        worker?.presenter = self.presenter
        worker?.postRequestForRosterDetails(request: request, method: method)
    }

    func doGetServiceListData(employeeId: String?) {
        worker = ListingWorker()
        worker?.presenter = self.presenter
        worker?.getRequestForServiceList(employeeId: employeeId)
    }
}
