//
//  ListingWorker.swift
//  Enrich_SMA
//
//  Created by Harshal on 14/07/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListingWorker {
    let networkLayer = NetworkLayerAlamofire() // Uncomment this in case do request using Alamofire for client request
    var presenter: ListingPresentationLogic?

    func postRequestForRosterDetails(request: MyProfile.GetRosterDetails.Request, method: HTTPMethod) {

        let errorHandler: (String) -> Void = { (error) in
            print(error)
            self.presenter?.presentError(responseError: error)
        }
        let successHandler: (MyProfile.GetRosterDetails.Response) -> Void = { (response) in
            print(response)
            self.presenter?.presentGetRosterDetailsSuccess(response: response)
        }

        self.networkLayer.post(urlString: ConstantAPINames.getEmployeeList.rawValue, body: request,
                               headers: ["X-Request-From": "tma"],
                               successHandler: successHandler, errorHandler: errorHandler, method: .post)

    }

    func getRequestForServiceList(employeeId: String?) {

        let errorHandler: (String) -> Void = { (error) in
            print(error)
            self.presenter?.presentError(responseError: error)
        }
        let successHandler: (MyProfile.GetServiceList.Response) -> Void = { (response) in
            print(response)
            self.presenter?.presentGetServiceListSuccess(response: response)
        }

        var url = ConstantAPINames.getServiceList.rawValue
        if let id = employeeId {
            url.append("&employee_id=\(id)")
        }

        self.networkLayer.get(urlString: url,
                              headers: ["Authorization": "Bearer \(GenericClass.sharedInstance.isuserLoggedIn().accessToken)"], successHandler: successHandler, errorHandler: errorHandler)

    }
}
