//
//  AppointmentFilterModels.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 09/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AppointmentFilter {
    // MARK: Use cases

    enum GetFilterDetails {
        struct Request: Codable {
            let salon_id: String?
            let date: String?
        }

        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
            let data: Data?
            let time_stamp: String?
        }

        struct Data: Codable {
            let status_list: [String]?
            let technician_list: [TechnicianList]?
        }

        struct TechnicianList: Codable {
            let id: Int64?
            let name: String?
        }
    }
}
