//
//  RevenueModels.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 11/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Revenue {
    // MARK: Use cases

    enum OneClickData {

        struct Request: Codable {
            let is_custom: Bool
            let salon_id: String
        }

        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
            var data: [Data]?
        }

        struct Data: Codable {
            let month: AnyCodable?
            let salon_id: AnyCodable?
            let entity_id: AnyCodable?
            let salon_name: AnyCodable?
            let status: AnyCodable?

            let service_revenue_current_year: AnyCodable?
            let service_revenue_previous_year: AnyCodable?
            let service_revenue_percent: AnyCodable?

            let products_revenue_current_year: AnyCodable?
            let products_revenue_previous_year: AnyCodable?
            let product_revenue_percent: AnyCodable?

            let yoy_revenue_growth_services_and_product: AnyCodable?
            let retail_products_as_percentage_to_services_revenue: AnyCodable?
            let salon_achievement_percentage: AnyCodable?

            let current_year_date: AnyCodable?
            let previous_year_date: AnyCodable?
            let rm_consumption: AnyCodable?

            let client_consultation_customer: AnyCodable?
            let consultation_percent: AnyCodable?

            let punctual_time_percent: AnyCodable?
        }
    }
}
