//
//  RevenueModels.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 11/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Revenue {
    // MARK: Use cases
    
    enum OneClickData {
        
        struct Request: Codable {
            let is_custom: Bool
            let salon_id: String
        }
        
        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
            var data: [Data]?
        }
        
        struct Data: Codable {
            let entity_id: AnyCodable?
            let salon_id: AnyCodable?
            let salon_name: AnyCodable?
            let target_table_salon_name: AnyCodable?
            let current_year_date: AnyCodable?
            let previous_year_date: AnyCodable?
            let service_revenue_current_year: AnyCodable?
            let service_revenue_previous_year: AnyCodable?
            let products_revenue_current_year: AnyCodable?
            let products_revenue_previous_year: AnyCodable?
            let yoy_revenue_growth_services_and_product: AnyCodable?
            let total_service_revenue: AnyCodable?
            let total_products_revenue: AnyCodable?
            let retail_products_as_percentage_to_services_revenue: AnyCodable?
            let salon_achievement_percentage: AnyCodable?
            let st_month: AnyCodable?
        }
    }
}
