//
//  SetNewPasswordInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 18/11/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SetNewPasswordBusinessLogic
{
  func doSomething(request: SetNewPassword.Something.Request)
}

protocol SetNewPasswordDataStore
{
  //var name: String { get set }
}

class SetNewPasswordInteractor: SetNewPasswordBusinessLogic, SetNewPasswordDataStore
{
  var presenter: SetNewPasswordPresentationLogic?
  var worker: SetNewPasswordWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SetNewPassword.Something.Request)
  {
    worker = SetNewPasswordWorker()
    worker?.doSomeWork()
    
    let response = SetNewPassword.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
