//
//  MyProfileInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 16/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyProfileBusinessLogic {
    func doGetMyProfileData(employeeId: Int?, accessToken: String, method: HTTPMethod)
    func doGetRosterData(request: MyProfile.GetRosterDetails.Request, method: HTTPMethod)
    func doGetServiceListData(accessToken: String, method: HTTPMethod)
}

protocol MyProfileDataStore {
    //var name: String { get set }
}

class MyProfileInteractor: MyProfileBusinessLogic, MyProfileDataStore {

    var presenter: MyProfilePresentationLogic?
    var worker: MyProfileWorker?
    //var name: String = ""

    // MARK: Do something
    func doGetMyProfileData(employeeId: Int?, accessToken: String, method: HTTPMethod) {
        worker = MyProfileWorker()
        worker?.presenter = self.presenter
        worker?.getRequestForUserProfile(employeeId: employeeId, accessToken: accessToken, method: method)
    }

    func doGetRosterData(request: MyProfile.GetRosterDetails.Request, method: HTTPMethod) {
        worker = MyProfileWorker()
        worker?.presenter = self.presenter
        worker?.postRequestForRosterDetails(request: request, method: method)
    }

    func doGetServiceListData(accessToken: String, method: HTTPMethod) {
        worker = MyProfileWorker()
        worker?.presenter = self.presenter
        worker?.getRequestForServiceList(accessToken: accessToken, method: method)
    }

}
