//
//  MyProfileModels.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 16/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MyProfile
{
    // MARK: Use cases
    
    enum GetUserProfile {
        
        struct Request: Codable {
            let is_custom: Bool = true
        }
        
        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
            var data: UserData?
        }
        
        struct UserData: Codable {
            var username: String?
            var admin_id: String?
            var firstname: String?
            var middlename: String?
            var lastname: String?
            var nickname: String?
            var employee_code: String?
            var birthdate: String?
            var designation: String?
            var base_salon_code: String?
            var base_salon_name: String?
            var joining_date: String?
            var category: String?
            var profile_pic: String?
            var rating: Double?
        }
    }
    
    enum GetServiceList {
        
        struct Request: Codable {
            let is_custom: Bool = true
        }
        
        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
            var data: Data?
        }
        
        struct Data: Codable {
            var service_count: Int?
            var service_list: [String]?
        }
    }
    
    enum GetRosterDetails {
        
        struct Request: Codable {
            let salon_code: String
            let fromDate: String
            let toDate: String
            let employee_code: String
        }
        
        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
            var data: [EmployeeData]?
            var time_stamp: String = ""
        }
        
        struct EmployeeData: Codable {
            let first_name: String?
            let last_name: String?
            let category_name: String?
            let shift_name: String?
            let start_time: String?
            let end_time: String?
            let date: String?
            let is_leave: Int?
            let leave_type_id: Int?
            let leave_type: String?
            let employee_id: Int?
            let roster_id: Int?
            let shift_id: Int?
            let designation: String?
            let rating: Double?
            let attendance_status: String?
        }
    }
    
}




