//
//  MyProfileWorker.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 16/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MyProfileWorker
{
    let networkLayer = NetworkLayerAlamofire() // Uncomment this in case do request using Alamofire for client request
    var presenter: MyProfilePresentationLogic?
    
    func getRequestForUserProfile(employeeId:Int?,accessToken:String, method: HTTPMethod) {
        
        let errorHandler: (String) -> Void = { (error) in
            print(error)
            self.presenter?.presentGetProfileError(responseError: error)
        }
        let successHandler: (MyProfile.GetUserProfile.Response) -> Void = { (response) in
            print(response)
            self.presenter?.presentGetProfileSuccess(response: response)
        }
        
        var url = ConstantAPINames.getUserProfile.rawValue
        if let id = employeeId{
            url.append("&employee_id=\(id)")
        }
        
        self.networkLayer.get(urlString: url, headers: ["Authorization": "Bearer \(accessToken)"], successHandler: successHandler, errorHandler: errorHandler)
        
    }
    
    func postRequestForServiceList(request:MyProfile.GetRosterDetails.Request, method: HTTPMethod) {
        
        let errorHandler: (String) -> Void = { (error) in
            print(error)
            self.presenter?.presentGetProfileError(responseError: error)
        }
        let successHandler: (MyProfile.GetRosterDetails.Response) -> Void = { (response) in
            print(response)
            self.presenter?.presentGetRosterDetailsSuccess(response: response)
        }
        
        self.networkLayer.post(urlString: ConstantAPINames.getEmployeeList.rawValue, body: request, headers: ["X-Request-From": "tma"], successHandler: successHandler, errorHandler: errorHandler, method: .post)
        
    }
    
    func getRequestForServiceList(accessToken:String, method: HTTPMethod) {
        
        let errorHandler: (String) -> Void = { (error) in
            print(error)
            self.presenter?.presentGetProfileError(responseError: error)
        }
        let successHandler: (MyProfile.GetServiceList.Response) -> Void = { (response) in
            print(response)
            self.presenter?.presentGetProfileSuccess(response: response)
        }
        
        self.networkLayer.get(urlString: ConstantAPINames.getServiceList.rawValue, headers: ["Authorization": "Bearer \(accessToken)"], successHandler: successHandler, errorHandler: errorHandler)
        
    }
}
