//
//  MyProfileModels.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 16/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MyProfile {
    // MARK: Use cases

    enum GetUserProfile {

        struct Request: Codable {
            let is_custom: Bool = true
        }

        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
            var data: UserData?
        }

        struct UserData: Codable {

            let username: String?
            let admin_id: String?
            let firstname: String?
            let middlename: String?
            let lastname: String?
            let nickname: String?
            let employee_code: String?
            let employee_id: String?
            let birthdate: String?
            let designation: String?
            let base_salon_code: String?
            let base_salon_name: String?
            let joining_date: String?
            let category: String?
            let profile_pic: String?
            let rating: AnyCodable?
            let mobile_number: String?
            let email: String?
            let address: [Address]?
            let gender: String?
            let salon_id: String?
            let work_number: String?
            let status: String?
            let customer_count: String?
            let bmt_incentive_dashboard_enabled: Bool?
        }

        struct Address: Codable {
            let line_1: String?
            let line_2: String?
            let city: String?
            let state: String?
            let country: String?
        }
    }

    enum GetServiceList {

        struct Request: Codable {
            let is_custom: Bool = true
        }

        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
            var data: Data?
        }

        struct Data: Codable {
            var service_count: Int?
            var service_list: [Service_list]?
        }

        struct Service_list: Codable {
            let entity_id: String?
            let type_id: String?
            let name: String?
            let price: Double?
            let service_id: String?
            let service_code: String?
            let store_id: Int64?
            let min_price: Double?
            let max_price: Double?
            let service_category: String?
            let service_time: String?
            let parent_item_id: String?
            let parent_name: String?
            let parent_sku: String?
            let product_type: String?
            let is_consultation_required: String?
            let bundle_parent_id: String?
            let configurable_parent_id: String?
        }
    }

    enum GetRosterDetails {

        struct Request: Codable {
            let salon_code: String
            let fromDate: String
            let toDate: String
            let employee_id: String
        }

        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
            var data: [EmployeeData]?
            var time_stamp: String = ""
        }

        struct EmployeeData: Codable {
            let first_name: String?
            let last_name: String?
            let category_name: String?
            let shift_name: String?
            let start_time: String?
            let end_time: String?
            let date: String?
            let is_leave: Int?
            let leave_type_id: Int?
            let leave_type: String?
            let employee_id: Int?
            let roster_id: Int?
            let shift_id: Int?
            let designation: String?
            let rating: Double?
            let attendance_status: String?
        }
    }

}
