//
//  MyProfileModels.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 16/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MyProfile
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
}

let profileSections:[MyProfileSection] =
    [MyProfileSection(title:"Personal details",data:[MyProfileModel(title:"Date of joining",value:"DD/MM/YYY",isMultiOption:false),
                                                     MyProfileModel(title:"Gender",value:"Male",isMultiOption:false),
                                                     MyProfileModel(title:"Mobile No",value:"9876532445",isMultiOption:false),
                                                     MyProfileModel(title:"Home Contact No",value:"020-27281174",isMultiOption:false),
                                                     MyProfileModel(title:"Email Id",value:"abc@gmail.com",isMultiOption:false),
                                                     MyProfileModel(title:"Passport No",value:"DFHH353456CV",isMultiOption:false),
                                                     MyProfileModel(title:"Address",value:"terad xdgfg adgdfhZC zdgdghvbvx fhgdb fhghfg xfgdfgdf",isMultiOption:false)]),
     MyProfileSection(title:"Professional details",data:[MyProfileModel(title:"Employee Code",value:"1234",isMultiOption:false),
                                                         MyProfileModel(title:"Nick Name",value:"Parmo",isMultiOption:false),
                                                         MyProfileModel(title:"Experience",value:"5 Years",isMultiOption:false),
                                                         MyProfileModel(title:"Center",value:"Aundh",isMultiOption:false),
                                                         MyProfileModel(title:"Category",value:"Hair",isMultiOption:false),
                                                         MyProfileModel(title:"Designation/Role",value:"Maste Stylist",isMultiOption:false),
                                                         MyProfileModel(title:"Services Performed",value:"Service 1,Service 2",isMultiOption:true)]),
     MyProfileSection(title:"Shift details",data:[MyProfileModel(title:"Working Hours",value:"10 Hour",isMultiOption:false),
                                                  MyProfileModel(title:"Shift Timing",value:"Shift 1(10.00 - 8.00)",isMultiOption:true),
                                                  MyProfileModel(title:"Working Hours",value:"10 Hour",isMultiOption:false),
                                                  MyProfileModel(title:"Status",value:"Active",isMultiOption:false)])]
