//
//  RevenuesPresenter.swift
//  Enrich_SMA
//
//  Created by Harshal on 25/01/22.
//  Copyright (c) 2022 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RevenuesPresentationLogic
{
  func presentSomething(response: Revenues.Something.Response)
}

class RevenuesPresenter: RevenuesPresentationLogic
{
  weak var viewController: RevenuesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Revenues.Something.Response)
  {
    let viewModel = Revenues.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
