//
//  ReportsModels.swift
//  Enrich_SMA
//
//  Created by Harshal Patil on 22/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Reports {
    // MARK: Use cases

    enum GetReports {

        struct Request: Codable {
        }

        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
            let data: [Category]?
        }

        struct Category: Codable {
            let categoryName: String?
            let links: [Data]?
        }

        struct Data: Codable {
            let type: String?
            let url: String?
        }
    }
}
