//
//  ApprovalRequestListInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 09/03/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ApprovalRequestListBusinessLogic {
  func doSomething(request: ApprovalRequestList.Something.Request)
}

protocol ApprovalRequestListDataStore {
  //var name: String { get set }
}

class ApprovalRequestListInteractor: ApprovalRequestListBusinessLogic, ApprovalRequestListDataStore {
  var presenter: ApprovalRequestListPresentationLogic?
  var worker: ApprovalRequestListWorker?
  //var name: String = ""

  // MARK: Do something

  func doSomething(request: ApprovalRequestList.Something.Request) {
    worker = ApprovalRequestListWorker()
    worker?.doSomeWork()

    let response = ApprovalRequestList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
