//
//  ApprovalRequestListPresenter.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 09/03/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ApprovalRequestListPresentationLogic {
  func presentSomething(response: ApprovalRequestList.Something.Response)
}

class ApprovalRequestListPresenter: ApprovalRequestListPresentationLogic {
  weak var viewController: ApprovalRequestListDisplayLogic?

  // MARK: Do something

  func presentSomething(response: ApprovalRequestList.Something.Response) {
    let viewModel = ApprovalRequestList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
